### ISSUE TITLE
Bug Fix: Fix Double Event Creation In delay between first click and resulting success toast

### ISSUE THREAD

**Issue by adnan-sami-raiyan** [CMPUT301F24mikasa/Event-Lottery-App#131]
> At the moment, in the time delay between clicking on "create event" button and the resulting toast message "Event created successfully", the user can click on the button twice and create duplicate events. 

- need to make the button unclickable as soon as it is clicked the first time. And only make it clickable a second time if the event was not created for some reason (for example, FireStore server connection issue, or invalid fields, or missing fields etc.)

**Comment by bdong5** [comment]
I'll do this later
